## Матрицы и матричные операции. Часть 1

In [1]:
import numpy as np

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;


$AB$ - определить нельзя<br>
$BA$ - определить нельзя

б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;

$AB = 2 \times 3$<br>
$BA$ - определить нельзя

в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;

$AB = 8 \times 8$<br> 
$BA = 3 \times 3$

г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

$AB = 4 \times 4$<br> 
$BA = 4 \times 4$

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$
A + B = \begin{pmatrix}
5 & -3\\
3 & 5
\end{pmatrix}
$

$
AB = \begin{pmatrix}
1 \cdot 4 - 2 \cdot 0 & -1 \cdot 1 - 2 \cdot 5 \\
3 \cdot 4 + 0 \cdot 0 & -1 \cdot 3 + 0 \cdot 5
\end{pmatrix}
=
\begin{pmatrix}
4 & -11 \\
12 & -3
\end{pmatrix}
$

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$
3A = \begin{pmatrix}
3 & 21 \\
9 & -18
\end{pmatrix}
$

$
2B =\begin{pmatrix}
0 & 10 \\
4 & -2
\end{pmatrix}
$

$
4C = \begin{pmatrix}
8 & -16 \\
4 & 4
\end{pmatrix}
$

$
3A - 2B + 4C = \begin{pmatrix}
11 & -5 \\
9 & -12
\end{pmatrix}
$

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

$
\begin{pmatrix}
4 & 1 \\
5 & -2 \\
2 & 3
\end{pmatrix}
\cdot
\begin{pmatrix}
4 & 5 & 2 \\
1 & -2 & 3
\end{pmatrix}
$

$
AA^T = \begin{pmatrix}
17 & 18 & 11 \\
18 & 29 & 4 \\
11 & 4 & 13
\end{pmatrix}
$

$
\begin{pmatrix}
4 & 5 & 2 \\
1 & -2 & 3
\end{pmatrix}
\cdot
\begin{pmatrix}
4 & 1 \\
5 & -2 \\
2 & 3
\end{pmatrix}
$

$
A^TA = \begin{pmatrix}
45 & 0 \\
0 & 14
\end{pmatrix}
$

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [2]:
A = np.array([[3, 2],[4, 1]])
B = np.array([[0, 8, 3],[4, 5, 4]])

In [3]:
A

array([[3, 2],
       [4, 1]])

In [4]:
B

array([[0, 8, 3],
       [4, 5, 4]])

In [5]:
def transpose(matrix: np.ndarray):
    '''function to transpose matrix'''
    
    index_x = range(matrix.shape[1]) # get index of x axis
    index_y = range(matrix.shape[0]) # get index of y axis
    
    result = []
    
    for i in index_x: # get every index in axis x
        y = []        # create empty y
        
        for j in index_y:         # now get every index in axis y
            y.append(matrix[j,i]) # and add to the previously created variable y, column j and row i
            
        result.append(y)
        
    return np.array(result)

In [6]:
def dot(matrix1, matrix2):
    '''function to scalar matrix multiplication'''
    
    t_matrix2 = transpose(matrix2)
    
    result = []
    
    for i in matrix1:
        y = []
        
        for j in t_matrix2:
            p = i*j
            y.append(p[0] + p[1])
            
        result.append(y)
            
    return np.array(result)

In [7]:
dot(A, B) # здесь есть проблема, которую я не успел решить - если умножить B на BT, то получится не правильный ответ

array([[ 8, 34, 17],
       [ 4, 37, 16]])

## Матрицы и матричные операции. Часть 2

__1.__ Вычислить определитель:

a)
$
\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};
$

$
sinx \cdot sinx = 1\\
-cosx \cdot cosx = 1\\
dot = 1 - 1 = 0
$


б)
$
\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};
$

Здесь треугольная матрица, поэтому перемножаем основную диагоняль<br>
$det = 4 \cdot 5 \cdot 9 = 180$

в)
$
\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.
$

Здесь можно привести к линейнозависимым строкам<br>
$
\begin{vmatrix}
1 & 2 & 1\\ 
4 & 5 & 1\\ 
7 & 8 & 1
\end{vmatrix}
$
=
$
\begin{vmatrix}
1 & 1 & 1\\ 
4 & 1 & 1\\ 
7 & 1 & 1
\end{vmatrix}
$<br>
$det = 0$

__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2}) = 16$;
    
   б) $det(A^{T}) = 4$;
    
   в) $det(2A) = 8$.

__3.__  Доказать, что матрица

$
\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}
$
   
вырожденная

Здесь вторая строка это на первая умноженная на $-2$, поэтому разделим вторую строку на $-2$

$
\begin{pmatrix}
-2 & 7 & -3\\ 
-2 & 7 & -3\\ 
-3 & 7 & 13
\end{pmatrix}
$

Первая и вторая строки линейно зависимы $\Rightarrow det = 0 \Rightarrow$ матрица вырожденная

__4.__ Найти ранг матрицы:

а) 
$
\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};
$

3я строка - это комбинация 1й и 2й, значит ей убираем

$
\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1
\end{pmatrix};
$

Ранг матрицы = 2

б) 
$
\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.
$

3я строка - это комбинация 1й и 2й, значит ей убираем

$
\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\  
2 & 3 & 5 & 6
\end{pmatrix}.
$

Ранг матрицы = 3