### Первая методичка

__1.__ Исследовать на линейную зависимость:
$$f_{1}(x)=e^{x}, f_{2}(x)=1, f_{3}(x)=x+1, f_{4}(x)=x-e^{x}.$$


$x-e^x = -1\cdot(e^x + 1) + x + 1 = -e^x -1 +x +1 = -e^x + x$

$f_4(x) = -1\cdot(f_1(x) + f_2(x)) + f_3(3)\ -$ вектора линейно зависимы

__2.__ Исследовать на линейную зависимость:
$$f_{1}(x)=2, f_{2}(x)=x, f_{3}(x)=x^{2}, f_{4}(x)=(x+1)^{2}.$$

Здесь не могу найти вариант, как доказать линейную комбинацию векторов, могу предположить, что эти вектора не зависимы.

__3.__ Найти координаты вектора $x = (2, 3, 5)\in \mathbb{R}^{3}$ в базисе $b_{1}=(0, 0, 10)$, $b_{2}=(2, 0, 0)$, $b_{3}=(0, 1, 0)$.

$x=(2,3,5) = (0,0,20)+(6,0,0)+(0,5,0) = 6e_1 + 5e_2 + 20e_3$

Координаты $x = (6,5,20)$

__4.__ Найти координаты вектора $3x^{2}-2x+2\in\mathbb{R}^{3}[x]$:

   а) в базисе $1$, $x$, $x^{2}$;

$
3\cdot x^2 - 2\cdot x + 0*1\\
(0, -2, 3)
$

б) в базисе $x^{2}$, $x-1$, $1$.

$
3\cdot x^2 - 2*(x-1) + 0\cdot 1\\
(3, -2, 0)
$

__5.__ Установить, является ли линейным подпространством:

а) совокупность всех векторов трехмерного пространства, у которых по крайней мере одна из первых двух координат равна нулю;

Является так с ними можно провести операции сложения и умножение векторов, даже если в итоге получится координата $(0,0)$ - это будет нулевым вектором. 
    
б) все векторы, являющиеся линейными комбинациями данных векторов $\{u_{1}, u_{2}, ..., u_{n}\}$.

Является если для данной системы векторов существует хотя бы 1 отличный от 0.

### Вторая методичка

__1.__ Найти скалярное произведение векторов $x, y \in \mathbb{R}$:<br>
а) $x=(0,-3, 6),~y=(-4, 7, 9);$<br>
б) $x=(7, -4, 0, 1),~y=(-3, 1, 11, 2).$

In [1]:
import numpy as np

In [2]:
x1 = [0,-3,6]
y1 = [-4,7,9]

x2 = [7,-4,0,1]
y2 = [-3,1,11,2]

In [3]:
a = np.dot(x1,y1)
b = np.dot(x2,y2)
a, b

(33, -23)

__2.__ Найти нормы векторов $(4, 2, 4)$ и $(12, 3, 4)$ и угол между ними.

In [4]:
from numpy.linalg import norm

In [5]:
A = [4,2,4]
B = [12,3,4]

In [6]:
am = sum([(a**2)**(1/2) for a in A])
bm = sum([(b**2)**(1/2) for b in B])

ae = sum([a**2 for a in A])**(1/2)
be = sum([b**2 for b in B])**(1/2)

In [7]:
am, bm # манхенненская норма

(10.0, 19.0)

In [8]:
ae, be # эвклидова норма

(6.0, 13.0)

In [9]:
cosfi = np.dot(A,B) / (norm(A) * norm(B))
cosfi # угол между векторами

0.8974358974358975

__3.__ Будет ли линейное пространство евклидовым, если за скалярное произведение принять:<br>
а) произведение длин векторов;<br>
Да, так как это первая аксиома $(x,y) = (y,x)$<br>
б) утроенное обычное скалярное произведение векторов?<br>
Да, так как это вторрая аксиома $(\lambda x,y) = \lambda(x,y)$

__4.__ Какие из нижеперечисленных векторов образуют ортонормированный базис в линейном пространстве $\mathbb{R}^{3}$:<br>
а) $(1,0,0),(0,0,1);$ <br>
б) $(1/\sqrt{2},-1/\sqrt{2},0),(1/\sqrt{2},1/\sqrt{2},0), (0,0,1);$<br>
в) $(1/2, -1/2, 0), (0, 1/2, 1/2), (0,0,1);$<br>
г) $(1,0,0),(0,1,0),(0,0,1)?$ 

In [10]:
# проверяем векторы а
a = np.array([(1,0,0),(0,0,1)])

e_1 = a[0]
a_2 = a[1]
a_1 = -np.dot(e_1, a_2)/np.dot(e_1,e_1)
e_2 = a_2 + np.dot(a_1, e_1)

e_1, e_2

(array([1, 0, 0]), array([0., 0., 1.]))

In [11]:
np.dot(e_1,e_2), norm(e_1), norm(e_2)

(0.0, 1.0, 1.0)

##### Произведение векторов $а=0$, нормы $e_1$ и $e_2 = 1$ - векаторы $а$ образуют ортогональный базис

In [12]:
def ort(a):
    '''функция для поиска эллементов базиса'''
    
    e_1 = a[0]
    a_2 = a[1]
    a_3 = a[2]

    a_1 = -np.dot(e_1, a_2)/np.dot(e_1,e_1)
    e_2 = a_2 + np.dot(a_1, e_1)

    a_1 = -np.dot(e_1, a_3)/np.dot(e_1,e_1)
    a_2 = -np.dot(e_2, a_3)/np.dot(e_2,e_2)
    e_3 = a_3 + np.dot(a_1, e_1) + np.dot(a_2, e_2)

    return e_1, e_2, e_3

In [13]:
def check(e):
    '''функция для проверки ортогональности базиса'''
    
    print(f'скаляры:\n'
          f'{np.dot(e[0], e[1])}\n'
          f'{np.dot(e[2], e[1])}\n'
          f'нормы:\n'
          f'{norm(e[0]), norm(e[1]), norm(e[2])}')

In [14]:
b = np.array([
    (1/2**(1/2), -1/2**(1/2), 0),
    (1/2**(1/2), 1/2**(1/2), 0),
    (0,0,1)
])

e = ort(b)
e

(array([ 0.70710678, -0.70710678,  0.        ]),
 array([0.70710678, 0.70710678, 0.        ]),
 array([0., 0., 1.]))

In [15]:
check(e)

скаляры:
0.0
0.0
нормы:
(0.9999999999999999, 0.9999999999999999, 1.0)


##### Произведение векторов $б=0$, нормы $e_1, e_2$ и $e_3 = 1$ - вектор $б$ образуют ортогональный базис

In [16]:
c = np.array([
    (1/2, -1/2, 0),
    (0, 1/2, 1/2),
    (0,0,1)
])

e = ort(c)
e

(array([ 0.5, -0.5,  0. ]),
 array([0.25, 0.25, 0.5 ]),
 array([-0.33333333, -0.33333333,  0.33333333]))

In [17]:
check(e)

скаляры:
0.0
2.7755575615628914e-17
нормы:
(0.7071067811865476, 0.6123724356957945, 0.5773502691896258)


##### Только 1е произведение верторов $= 0$, и нормы $\neq 1$ - векторы $в$ не образуеют ортогональный базис 

In [18]:
d = np.array([
    (1,0,0),
    (0,1,0),
    (0,0,1)
])

e = ort(d)
e

(array([1, 0, 0]), array([0., 1., 0.]), array([0., 0., 1.]))

In [19]:
check(e)

скаляры:
0.0
0.0
нормы:
(1.0, 1.0, 1.0)


##### Произведение векторов $г=0$, нормы $e_1, e_2$ и $e_3 = 1$ - векторы $г$ образуют ортогональный базис